spawn = require('child_process').spawn
child = undefined

task 'run', 'Runs the server', ->
  command = 'coffee'
  args = ['app/server.coffee', '-w', '-s']
  child = spawn command, args, stdio: 'inherit'

process.on 'SIGTERM', ->
  child.kill 'SIGTERM'
