spawn = require('child_process').spawn

task 'run', 'Runs the server', ->
	command = 'coffee'
    args = ['app/server.coffee']
	child = spawn command, args, stdio: 'inherit'

process.on 'SIGTERM', ->
	child.kill 'SIGTERM'
